### ISSUE TITLE
The hamburger menu doesn't seem to be working

### ISSUE THREAD

**Issue by Jantje19** [simplyGits/simplyHomework.nl#11]
The hamburger menu doesn't seem to be working. When I try to click on it it does nothing

**Comment by lieuwex** [comment]
Thank you for your report! This is a known problem, a fix is being tested and will, if everything goes according to plan, be deployed soon!

**Comment by lieuwex** [comment]
@Jantje19 This should be fixed now, could you check if that's the case?

**Comment by Jantje19** [comment]
It works now. Thanks

**Comment by lieuwex** [comment]
Glad to hear!
